package com.timmat.financetracker.data.repository

import android.content.Context
import android.content.SharedPreferences
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import dagger.hilt.android.qualifiers.ApplicationContext
import java.security.SecureRandom
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Secure storage for the app-lock PIN.
 *
 * Hardening choices:
 *  * **PBKDF2-HMAC-SHA256 with 120 000 iterations** — slow to brute-force offline.
 *  * Per-install random 16-byte **salt**, generated by [SecureRandom].
 *  * All values live in `EncryptedSharedPreferences` (Android Keystore-backed
 *    AES-256-GCM) — encrypted at rest, tied to the device.
 *  * **Constant-time** comparison when verifying.
 *  * **Rate-limiting**: after [MAX_ATTEMPTS] consecutive failures the lock
 *    screen enforces a [LOCKOUT_MS] cool-down. The counter is persisted so
 *    a restart cannot bypass it.
 */
@Singleton
class AppLockRepository @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    private val prefs: SharedPreferences by lazy {
        val masterKey = MasterKey.Builder(context)
            .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
            .build()
        EncryptedSharedPreferences.create(
            context,
            PREFS_NAME,
            masterKey,
            EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
            EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM,
        )
    }

    fun isPinSet(): Boolean =
        prefs.contains(KEY_HASH) && prefs.contains(KEY_SALT)

    /** Returns the length the saved PIN has (4–6). 0 if none set. */
    fun savedPinLength(): Int = prefs.getInt(KEY_PIN_LENGTH, 0)

    fun setPin(pin: String) {
        require(pin.length in 4..6 && pin.all { it.isDigit() }) { "PIN must be 4–6 digits" }
        val salt = ByteArray(16).also { SecureRandom().nextBytes(it) }
        val hash = hash(pin, salt)
        prefs.edit()
            .putString(KEY_HASH, hash.toHex())
            .putString(KEY_SALT, salt.toHex())
            .putInt(KEY_PIN_LENGTH, pin.length)
            .remove(KEY_FAIL_COUNT)
            .remove(KEY_LOCKED_UNTIL)
            .apply()
    }

    /**
     * Verifies [pin] against the stored hash. On success the fail counter is
     * cleared; on failure the counter is incremented and a lockout may be started.
     *
     * @return `true` iff the pin matches.
     */
    fun verifyPin(pin: String): Boolean {
        if (!isPinSet()) return false
        val storedHash = prefs.getString(KEY_HASH, null) ?: return false
        val saltHex = prefs.getString(KEY_SALT, null) ?: return false
        val salt = saltHex.fromHex()
        val candidate = hash(pin, salt).toHex()
        val matches = constantTimeEquals(candidate, storedHash)
        if (matches) {
            prefs.edit().remove(KEY_FAIL_COUNT).remove(KEY_LOCKED_UNTIL).apply()
        } else {
            recordFailure()
        }
        return matches
    }

    fun clear() {
        prefs.edit()
            .remove(KEY_HASH).remove(KEY_SALT).remove(KEY_PIN_LENGTH)
            .remove(KEY_FAIL_COUNT).remove(KEY_LOCKED_UNTIL)
            .apply()
    }

    // -------- Rate limiting --------

    /** Epoch-millis until which further PIN attempts are ignored. 0 = not locked out. */
    fun lockedUntilMs(): Long = prefs.getLong(KEY_LOCKED_UNTIL, 0L)

    fun failedAttemptCount(): Int = prefs.getInt(KEY_FAIL_COUNT, 0)

    private fun recordFailure() {
        val count = prefs.getInt(KEY_FAIL_COUNT, 0) + 1
        val editor = prefs.edit().putInt(KEY_FAIL_COUNT, count)
        if (count >= MAX_ATTEMPTS) {
            // Each further cohort of MAX_ATTEMPTS fails doubles the lockout, capped.
            val cycles = count / MAX_ATTEMPTS
            val penalty = LOCKOUT_MS * (1L shl (cycles - 1).coerceAtMost(4))
            editor.putLong(KEY_LOCKED_UNTIL, System.currentTimeMillis() + penalty)
        }
        editor.apply()
    }

    // -------- Helpers --------

    private fun hash(pin: String, salt: ByteArray): ByteArray {
        val spec = PBEKeySpec(pin.toCharArray(), salt, PBKDF2_ITER, 256)
        val factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
        return factory.generateSecret(spec).encoded
    }

    private fun constantTimeEquals(a: String, b: String): Boolean {
        if (a.length != b.length) return false
        var diff = 0
        for (i in a.indices) diff = diff or (a[i].code xor b[i].code)
        return diff == 0
    }

    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }

    private fun String.fromHex(): ByteArray {
        require(length % 2 == 0) { "Invalid hex" }
        return ByteArray(length / 2) { i ->
            ((Character.digit(this[i * 2], 16) shl 4) + Character.digit(this[i * 2 + 1], 16)).toByte()
        }
    }

    private companion object {
        const val PREFS_NAME = "finance_tracker_lock_secure"
        const val KEY_HASH = "pin_hash"
        const val KEY_SALT = "pin_salt"
        const val KEY_PIN_LENGTH = "pin_length"
        const val KEY_FAIL_COUNT = "pin_fail_count"
        const val KEY_LOCKED_UNTIL = "pin_locked_until"
        const val PBKDF2_ITER = 120_000
        const val MAX_ATTEMPTS = 5
        const val LOCKOUT_MS = 30_000L // 30s, doubles each block of MAX_ATTEMPTS fails
    }
}
